show/urls.py
from django.urls import path,re_path
from show import views

app_name='show'

urlpatterns=[
    path('index.html',views.index,name='index'),
    path('get_res/',views.get_res,name='get_res'),
]

webforshow/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('show/',include('show.urls',namespace='show')),
]

show/models.py
from django.db import models

# Create your models here.

show/views.py
from django.shortcuts import render
from django.http import JsonResponse
# Create your views here.
from .get_translation.load_tran import Translation

data_path=""
model_path=""
model=Translation(data_path,model_path)


def get_res(request):
    req_get=request.GET
    src=req_get['src']
    lab=req_get['lab']
    tgt=model.get_trans(src+lab)
    return JsonResponse({'tgt':tgt})

def index(request):
    return render(request,'index.html')

show/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static "jquery-3.4.1.min.js" %}"></script>
    <script>
        $(document).ready(function () {
             $('#get_res').click(function () {
                 var src=$('#in').val();
                 var lab=$('#lab').val();
                 $.getJSON('{% url 'show:get_res' %}',{'src':src,'lab':lab},function (ret) {
                     $('#out').val(ret.tgt)
                 })
             })
         })
    </script>
</head>
<body>
<h>INPUT</h>
<p></p>
<textarea id="in" rows=5 cols=40 style="background-color: antiquewhite ;font-size: 20px;color:black"></textarea>
<p></p>
<textarea id="lab" rows="1" cols="20" style="background-color: antiquewhite ;font-size: 20px;color:black"></textarea>
<p></p>
<input id="get_res" type="submit" value="trans">
<p></p>
<textarea id="out" rows=5 cols=40 style="background-color: antiquewhite ;font-size: 20px;color:black"readonly="readonly"></textarea>
</body>
</html>